### ISSUE TITLE
Network profile not found on RHV provider after upgrade to Cloudforms 4.7

### ISSUE THREAD

**Issue by sigbjornaib** [RedHatOfficial/miq-RedHat-Satellite6#86]
After an upgrade to Cloudforms 4.7, a network error happens every time a machine is attempted to be provisioned. The "myvmnetwork1" still exists, the only change was the upgrade from 4.6 to 4.7. 

The VM is cloned successfully, and the error seem to be occurring when CFME attempts to set the vnic profile on the VM.

[----] E, [2019-02-19T14:27:51.395260 #15614:11e5310] ERROR -- : Q-task_id([r1000000000320_miq_provision_1000000000393]) <AEMethod update_provision_status> VM Provision Error: [cfme1worker5] VM [testvm1.example.com] Step [CheckProvisioned] Status [[MiqException::MiqProvisionError]: Unable to find specified profile: <myvmnetwork1>] Message [[MiqException::MiqProvisionError]: Unable to find specified profile: <myvmnetwork1>]

**Comment by sigbjornaib** [comment]
This is in relation to an issue I had when setting up Cloudforms where "set_network" was not being called, resulting in the VMs NIC not getting any Network Profile set. I had some assistance where I was advised to add "/Infrastructure/VM/Provisioning/StateMachines/Methods/set_network" to "/ Infrastructure / VM / Provisioning / StateMachines / VMProvision_VM / satellite"

Disabling the automate domain where I have the override for "/ Infrastructure / VM / Provisioning / StateMachines / VMProvision_VM / satellite" allows the provisioning to continue, however I'm back to the VM not getting it's Network Profile set.

**Comment by sigbjornaib** [comment]
[----] I, [2019-02-21T19:52:24.838673 #12274:1160f5c]  INFO -- : Q-task_id([r1000000000339_miq_provision_1000000000421]) Updated namespace [Infrastructure/VM/RedHat/Utils  RedHatConsulting_Utilities/Infrastructure/VM]
[----] I, [2019-02-21T19:52:24.875708 #12274:1160f5c]  INFO -- : Q-task_id([r1000000000339_miq_provision_1000000000421]) Loading embedded method /RedHatConsulting_Utilities/Infrastructure/VM/RedHat/Utils
[----] I, [2019-02-21T19:52:24.877100 #12274:1160f5c]  INFO -- : Q-task_id([r1000000000339_miq_provision_1000000000421]) <AEMethod [/RedHatConsulting_Utilities/Infrastructure/VM/Provisioning/StateMachines/Methods/set_network]> Starting
[----] E, [2019-02-21T19:52:25.517331 #12274:122dbd8] ERROR -- : Q-task_id([r1000000000339_miq_provision_1000000000421]) <AEMethod set_network> The following error occurred during method evaluation:
[----] E, [2019-02-21T19:52:25.518190 #12274:122dbd8] ERROR -- : Q-task_id([r1000000000339_miq_provision_1000000000421]) <AEMethod set_network>   RuntimeError: service_template_provision_task not found
[----] E, [2019-02-21T19:52:25.520481 #12274:122dbd8] ERROR -- : Q-task_id([r1000000000339_miq_provision_1000000000421]) <AEMethod set_network>   /RedHatConsulting_Utilities/StdLib/Core/Core:109:in `get_stp_task'
/RedHatConsulting_Utilities/StdLib/Core/Core:10:in `initialize'
/RedHatConsulting_Utilities/Infrastructure/VM/Provisioning/StateMachines/Methods/set_network:102:in `new'
[----] E, [2019-02-21T19:52:25.532199 #12274:122dbd8] ERROR -- : Q-task_id([r1000000000339_miq_provision_1000000000421]) Method STDERR: /RedHatConsulting_Utilities/StdLib/Core/Core:109:in `get_stp_task': service_template_provision_task not found (RuntimeError)
[----] E, [2019-02-21T19:52:25.532901 #12274:122dbd8] ERROR -- : Q-task_id([r1000000000339_miq_provision_1000000000421]) Method STDERR: 	from /RedHatConsulting_Utilities/StdLib/Core/Core:10:in `initialize'
[----] E, [2019-02-21T19:52:25.533399 #12274:122dbd8] ERROR -- : Q-task_id([r1000000000339_miq_provision_1000000000421]) Method STDERR: 	from /RedHatConsulting_Utilities/Infrastructure/VM/Provisioning/StateMachines/Methods/set_network:102:in `new'
[----] E, [2019-02-21T19:52:25.533993 #12274:122dbd8] ERROR -- : Q-task_id([r1000000000339_miq_provision_1000000000421]) Method STDERR: 	from /RedHatConsulting_Utilities/Infrastructure/VM/Provisioning/StateMachines/Methods/set_network:102:in `<main>'
[----] I, [2019-02-21T19:52:25.593517 #12274:1160f5c]  INFO -- : Q-task_id([r1000000000339_miq_provision_1000000000421]) <AEMethod [/RedHatConsulting_Utilities/Infrastructure/VM/Provisioning/StateMachines/Methods/set_network]> Ending
[----] E, [2019-02-21T19:52:25.594133 #12274:1160f5c] ERROR -- : Q-task_id([r1000000000339_miq_provision_1000000000421]) Aborting instantiation (unknown method return code) because [Method exited with rc=Unknown RC: [1]]
[----] E, [2019-02-21T19:52:25.594706 #12274:1160f5c] ERROR -- : Q-task_id([r1000000000339_miq_provision_1000000000421]) State=<PreProvision_2> running  raised exception: <Method exited with rc=Unknown RC: [1]>
[----] W, [2019-02-21T19:52:25.594890 #12274:1160f5c]  WARN -- : Q-task_id([r1000000000339_miq_provision_1000000000421]) Error in State=[PreProvision_2]
[----] I, [2019-02-21T19:52:25.595209 #12274:1160f5c]  INFO -- : Q-task_id([r1000000000339_miq_provision_1000000000421]) In State=[PreProvision_2], invoking [on_error] method=[update_provision_status(status => 'Error configuring network interface preprovision: State=<PreProvision_2> running  raised exception: <Method exited with rc=Unknown RC: [1]>')]

**Comment by itewk** [comment]
well the root cause seems to be:
```
[----] E, [2019-02-21T19:52:25.518190 #12274:122dbd8] ERROR -- : Q-task_id([r1000000000339_miq_provision_1000000000421]) RuntimeError: service_template_provision_task not found
```

but the question is why isn't `service_template_provision_task` found.....

**Comment by itewk** [comment]
@sigbjornaib does your copy of miq-Utilities have https://github.com/RedHatOfficial/miq-Utilities/blame/master/Automate/RedHatConsulting_Utilities/StdLib/Core.class/__methods__/core.rb#L10 ?

Which version release of miq-Utilities do you currently have synced to your envionrment?

**Comment by sigbjornaib** [comment]
I have currently deployed the latest tagged version v11.5. Is that code present in version 11.5?

**Comment by itewk** [comment]
@sigbjornaib it should be, but it also should be preventing this error from happening. Can you manually inspect that you have that line in your copy of the code?

**Comment by sigbjornaib** [comment]
Yes I can. 
I have looked at our code, and line 10 does not have any "rescue nil" statement.

**Comment by sigbjornaib** [comment]
I notice that I had version 11.2 imported, not 11.5. When I go to Automation -> Automate -> Import/Export and add the url for the repo, and select import by tag I versions:
--
v1.0
v10.0
v10.1
v11.0
v11.1
v11.2
--

To see version v11.5 I have to scroll to the bottom where I find the following versions:
--
v11.3
v11.4
v11.5
--

After importing version v11.5 I get a bit further, however I still get an error: 

[----] I, [2019-02-25T10:01:14.789249 #12266:1160f5c]  INFO -- : Q-task_id([r1000000000349_miq_provision_1000000000431]) Updated namespace [miqaedb:/Infrastructure/VM/Provisioning/StateMachines/Methods/CheckProvisioned#create  ManageIQ/Infrastructure/VM/Provisioning/StateMachines]
[----] I, [2019-02-25T10:01:16.865999 #12266:1160f5c]  INFO -- : Q-task_id([r1000000000349_miq_provision_1000000000431]) Updated namespace [Infrastructure/VM/Provisioning/StateMachines/Methods/check_provisioned  ManageIQ/Infrastructure/VM/Provisioning/StateMachines]
[----] I, [2019-02-25T10:01:16.872727 #12266:1160f5c]  INFO -- : Q-task_id([r1000000000349_miq_provision_1000000000431]) Invoking [inline] method [/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/Methods/check_provisioned] with inputs [{}]
[----] I, [2019-02-25T10:01:16.873901 #12266:1160f5c]  INFO -- : Q-task_id([r1000000000349_miq_provision_1000000000431]) <AEMethod [/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/Methods/check_provisioned]> Starting
[----] I, [2019-02-25T10:01:17.346451 #12266:1150dc8]  INFO -- : Q-task_id([r1000000000349_miq_provision_1000000000431]) <AEMethod check_provisioned> ProvisionCheck returned <error> for state <finished> and status <Error>
[----] E, [2019-02-25T10:01:17.352902 #12266:1150dc8] ERROR -- : Q-task_id([r1000000000349_miq_provision_1000000000431]) <AEMethod check_provisioned> ProvisionCheck error <[MiqException::MiqProvisionError]: Unable to find specified profile: <mynetworklabel>>
[----] I, [2019-02-25T10:01:17.387443 #12266:1160f5c]  INFO -- : Q-task_id([r1000000000349_miq_provision_1000000000431]) <AEMethod [/ManageIQ/Infrastructure/VM/Provisioning/StateMachines/Methods/check_provisioned]> Ending
[----] I, [2019-02-25T10:01:17.387635 #12266:1160f5c]  INFO -- : Q-task_id([r1000000000349_miq_provision_1000000000431]) Method exited with rc=MIQ_OK
[----] I, [2019-02-25T10:01:17.388073 #12266:1160f5c]  INFO -- : Q-task_id([r1000000000349_miq_provision_1000000000431]) Followed  Relationship [miqaedb:/Infrastructure/VM/Provisioning/StateMachines/Methods/CheckProvisioned#create]
[----] I, [2019-02-25T10:01:17.388177 #12266:1160f5c]  INFO -- : Q-task_id([r1000000000349_miq_provision_1000000000431]) Processed State=[CheckProvisioned] with Result=[error]
[----] W, [2019-02-25T10:01:17.388291 #12266:1160f5c]  WARN -- : Q-task_id([r1000000000349_miq_provision_1000000000431]) Error in State=[CheckProvisioned]
[----] I, [2019-02-25T10:01:17.388574 #12266:1160f5c]  INFO -- : Q-task_id([r1000000000349_miq_provision_1000000000431]) In State=[CheckProvisioned], invoking [on_error] method=[update_provision_status(status => '[MiqException::MiqProvisionError]: Unable to find specified profile: <mynetworklabel>')]

I have verified that the network profile does indeed exist on the hypervisor selected by the method "/RedHatConsulting_Utilities/Infrastructure/VM/Provisioning/Placement/redhat_best_placement_with_scope". If I log in to RHV-M I can select the network manually by editing the VM created by CFME.

**Comment by itewk** [comment]
@sigbjornaib i assume this is related to https://github.com/RedHatOfficial/miq-Utilities/issues/140 in some way. But I am not seeing how it would be possible for you to select a network that isn't on the cluster that your VM is on due to how https://github.com/RedHatOfficial/miq-Utilities/blob/master/Automate/RedHatConsulting_Utilities/Service/Provisioning/DynamicDialogs.class/__methods__/get_networks.rb is written.

I would need to know more about the specifics of the location tag being selected, the os tag being selected, which template is tagged with that OS tag, which provider is tagged with the location tag, which cluster the template is on, and your `Infrastructure/Network/Configuration` instances.

**Comment by sigbjornaib** [comment]
@itewk no these two issues are not related. To prevent 
[miq-Utilities#140](https://github.com/RedHatOfficial/miq-Utilities/issues/140) from occuring we have currently only hosts in a single cluster tagged with the Prov Scope tag. 

This issue started after the upgrade to CF 4.7. 

Currently only one template is labeled with the os tag. The provider which contains the template is labeled with the same Location tag. Only 1 provider contains that Location tag. The template is on the same cluster as the hosts having the prov scope tag set to "All".

The instance under 'Infrastructure/Network/Configuration' is still the same, no networks has been added or removed since the upgrade to CF 4.7 was performed.

I would be able to send you logs and screenshots of what you require, if I can send them to you privately. Do you have anywhere I may contact you?

**Comment by itewk** [comment]
@sigbjornaib itewk@redhat.com

**Comment by sigbjornaib** [comment]
@itewk, I've sent you an email with the requested details.

**Comment by sigbjornaib** [comment]
I notice something interesting. Line #79 of set_network.rb says:
--
if (template.ext_management_system.type =~ /Redhat/) && (@handle.root['miq_server'].version >= '5.9')
--
And want to use a vnic_profile_id. The else is handled in line 83.
 
The debug output is supposed to be:
--
prov.set_vlan: vnic_profile_id …
--
But it looks like the if in #79 does not match, as the output in the log is
--
prov.set_vlan: provisioning_network_name …
--

**Comment by sigbjornaib** [comment]
So I changed the set_network.rb#79 from 5.9 to 5.10:
                    if (template.ext_management_system.type =~ /Redhat/) && (@handle.root['miq_server'].version >= '5.10')
 
Now the debug output says:

prov.set_vlan: vnic_profile_id =>

 
And guess what happened? It worked! 😊

**Comment by itewk** [comment]
This issue is actauly in miq-Utilities. opened PR to fix. clsoing this.

https://github.com/RedHatOfficial/miq-Utilities/pull/147
