### ISSUE TITLE
unable to set location_tag correctly / dialog_templates: INVALID SELECTION

### ISSUE THREAD

**Issue by shs-mdro** [RedHatOfficial/miq-RedHat-Satellite6#92]
Hi Guys & Girls

I've set up a test environment according to your guide, but i'm unable to deploy a vm.
log says that "Selected templates must be specified" and "dialog_templates" comes in with "INVALID SELECTION".

I guess it goes way back to the method "get_domains_by_location", where i get:

[----] I, [2019-06-05T11:47:01.844780 #6986:dce1578]  INFO -- : <AEMethod get_domains_by_location> location_index => {"total"=>3, "subtotal"=>3, "page"=>1, "per_page"=>20, "search"=>nil, "sort"=>{"by"=>nil, "order"=>nil}, "results"=>[{"ancestry"=>nil, "parent_id"=>nil, "parent_name"=>nil, "created_at"=>"2019-05-28 12:47:10 UTC", "updated_at"=>"2019-06-05 08:10:46 UTC", "id"=>3, "name"=>"BS", "title"=>"BS", "description"=>"BS"}, {"ancestry"=>nil, "parent_id"=>nil, "parent_name"=>nil, "created_at"=>"2019-05-24 14:52:46 UTC", "updated_at"=>"2019-05-24 14:52:46 UTC", "id"=>2, "name"=>"Default Location", "title"=>"Default Location", "description"=>nil}, {"ancestry"=>nil, "parent_id"=>nil, "parent_name"=>nil, "created_at"=>"2019-05-28 13:27:49 UTC", "updated_at"=>"2019-06-05 08:10:59 UTC", "id"=>6, "name"=>"ZH", "title"=>"ZH", "description"=>"ZH"}]}
[----] E, [2019-06-05T11:47:01.845715 #6986:dce1578] ERROR -- : <AEMethod get_domains_by_location> The following error occurred during method evaluation:
[----] E, [2019-06-05T11:47:01.848092 #6986:dce1578] ERROR -- : <AEMethod get_domains_by_location>   NoMethodError: undefined method `name' for nil:NilClass
[----] E, [2019-06-05T11:47:01.851510 #6986:dce1578] ERROR -- : <AEMethod get_domains_by_location>   /Configuration/Integration/Satellite/DynamicDialogs/get_domains_by_location:152:in `block in <main>'
/Configuration/Integration/Satellite/DynamicDialogs/get_domains_by_location:152:in `each'
/Configuration/Integration/Satellite/DynamicDialogs/get_domains_by_location:152:in `find'
[----] E, [2019-06-05T11:47:01.868263 #6986:dce1578] ERROR -- : Method STDERR: /Configuration/Integration/Satellite/DynamicDialogs/get_domains_by_location:152:in `block in <main>': undefined method `name' for nil:NilClass (NoMethodError)
[----] E, [2019-06-05T11:47:01.868978 #6986:dce1578] ERROR -- : Method STDERR:  from /Configuration/Integration/Satellite/DynamicDialogs/get_domains_by_location:152:in `each'
[----] E, [2019-06-05T11:47:01.869726 #6986:dce1578] ERROR -- : Method STDERR:  from /Configuration/Integration/Satellite/DynamicDialogs/get_domains_by_location:152:in `find'
[----] E, [2019-06-05T11:47:01.870448 #6986:dce1578] ERROR -- : Method STDERR:  from /Configuration/Integration/Satellite/DynamicDialogs/get_domains_by_location:152:in `<main>'
[----] I, [2019-06-05T11:47:01.951456 #6986:5734b14]  INFO -- : <AEMethod [/Configuration/Integration/Satellite/DynamicDialogs/get_domains_by_location]> Ending
[----] E, [2019-06-05T11:47:01.952461 #6986:5734b14] ERROR -- : Aborting instantiation (unknown method return code) because [Method exited with rc=Unknown RC: [1]]

Satellite has 3 test orgs and 2 locations, 1 org used for test deployments has both locations associated.
vsphere- and sat-provider have both locations and all environments allocated. the vsphere rhel7 template has right os tags (test-wise also both locations and all env-tags).

Do you have any idea why it can't enumerate "location_tag.name"?

The thing is, i can select a location in the service dialog, but the error above shifts dialog_templates into INVALID SELECTION, because "dialog_location_tags: ["[]"]" and this also doesn't get corrected afterwards while i select manually an available location from drop-down.

Would be great if you could help me out!

Thank you!
[automation.log](https://github.com/RedHatOfficial/miq-RedHat-Satellite6/files/3256576/automation.log)
[evm.log](https://github.com/RedHatOfficial/miq-RedHat-Satellite6/files/3256577/evm.log)

**Comment by itewk** [comment]
@curt-matthews or at @A-Beck either of you ahve some bandwidth to help @shs-mdro out?

**Comment by shs-mdro** [comment]
small update:
master branch used on both repos (miq-RedHat-Satellite6 & miq-Utilities)
satellite 6.4
cloudforms 5.10
vsphere 6.7

**Comment by itewk** [comment]
@curt-matthews @A-Beck ping.

**Comment by A-Beck** [comment]
@itewk I should be able to dig into this later this week/early next week.

@shs-mdro thanks for uploading the logs.

Looking at the output, here is what I see when the template dialog element attempts to populate:

```
[----] I, [2019-06-05T11:46:59.983767 #6986:d63475c]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> os_tag        => os/rhel7
[----] I, [2019-06-05T11:46:59.984196 #6986:d63475c]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> location_tags => ["[]"]
[----] I, [2019-06-05T11:46:59.984619 #6986:d63475c]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> providers_by_tag              => {}
[----] I, [2019-06-05T11:46:59.986274 #6986:d63475c]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> value => INVALID SELECTION
    * Destination location(s) must be selected to determine valid destination providers.
```

So it appears, like you were saying, that the location is not getting passed along properly.

Just to be clear, you are using the satellite dialog included in this repository, correct? 
-https://github.com/RedHatOfficial/miq-RedHat-Satellite6/blob/master/Dialogs/v5.9/Satellite_Provisioning.yml

If you get a chance, could you put '/Integration/Satellite/DynamicDialogs/get_locations_by_tag_path` in debug, and upload the resulting automation.log? It is odd behavior that you're able to select a location, but it does not appear available to the other dialog elements.

One thing you could do to allow for additional testing is to display the refresh button on the dialog elements ( see screen capture below ). That would allow for manual refreshing after the location dialog element is updated.

![image](https://user-images.githubusercontent.com/4661604/59041102-fa999180-8845-11e9-8700-a4abbd3bf633.png)

**Comment by shs-mdro** [comment]
Yes, I'm using the mentioned satellite dialog for provisioning.
Attached the new automation.log with debug@get_locations_by_tag_path.

My "Providers & Templates"-field looks a bit different, and since I've added the refresh button, the domain below doesn't get populated
[automation.log](https://github.com/RedHatOfficial/miq-RedHat-Satellite6/files/3264883/automation.log)

![image](https://user-images.githubusercontent.com/51401910/59088536-149ba880-8908-11e9-80e6-8ecb5115044c.png)

**Comment by A-Beck** [comment]
@shs-mdro Thanks for getting back so quickly.

I stood up a new CFME appliance, and unfortunately the custom dialogs are working as expected for me without any changes.

With a location not selected:
`<AEMethod get_domains_by_location> location_tags => ["[]"]`
After selecting a location, the domain and template dialog elements update
`<AEMethod get_domains_by_location> location_tags => ["location/my_location"]`

What is the exact version of CFME that you are on? Here is what I am testing on:

```
[root@localhost ~]# rpm -qa cfme*
cfme-gemset-5.10.4.2-1.el7cf.x86_64
cfme-appliance-common-5.10.4.2-1.el7cf.x86_64
cfme-5.10.4.2-1.el7cf.x86_64
cfme-appliance-tools-5.10.4.2-1.el7cf.x86_64
cfme-appliance-5.10.4.2-1.el7cf.x86_64
```

It looks like some versions of 5.10 were bitten by some bugs that would disrupt custom dialogs:
- i.e https://bugzilla.redhat.com/show_bug.cgi?id=1698586

**Comment by shs-mdro** [comment]
[root@cloudforms ~]# rpm -qa cfme*
cfme-5.10.4.2-1.el7cf.x86_64
cfme-gemset-5.10.4.2-1.el7cf.x86_64
cfme-appliance-common-5.10.4.2-1.el7cf.x86_64
cfme-appliance-tools-5.10.4.2-1.el7cf.x86_64
cfme-appliance-5.10.4.2-1.el7cf.x86_64

looks identical to me.

**Comment by shs-mdro** [comment]
I'm still wondering why your service dialog looks different than mine.
Originally i tried to import catalogs and dialogs according to the INSTALL.md like this:

[root@cloudforms ~]# git clone https://github.com/RedHatOfficial/miq-RedHat-Satellite6.git
Cloning into 'miq-RedHat-Satellite6'...
remote: Enumerating objects: 1245, done.
remote: Total 1245 (delta 0), reused 0 (delta 0), pack-reused 1245
Receiving objects: 100% (1245/1245), 213.51 KiB | 0 bytes/s, done.
Resolving deltas: 100% (609/609), done.
[root@cloudforms ~]# miqimport service_dialogs miq-RedHat-Satellite6/Dialogs/
rake aborted!
Errno::EISDIR: Is a directory @ io_fillbuf - fd:31 /root/miq-RedHat-Satellite6/Dialogs/v5.8
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:38:in `import_dialogs_from_file'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:29:in `block (2 levels) in import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:27:in `foreach'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:27:in `block in import'
/opt/rh/cfme-gemset/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/opt/rh/cfme-gemset/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/opt/rh/cfme-gemset/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/opt/rh/cfme-gemset/gems/activerecord-5.0.7.2/lib/active_record/transactions.rb:211:in `transaction'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:26:in `import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_dialogs.rake:202:in `block (3 levels) in <top (required)>'
Tasks: TOP => rhconsulting:service_dialogs:import
(See full trace by running task with --trace)

But as you can see it gives me an error and i tried to do a workaround by going on level deeper:

[root@cloudforms ~]# miqimport service_dialogs miq-RedHat-Satellite6/Dialogs/v5.9/
Dialog: [Satellite Provisioning]
Dialog: [Satellite Provisioning (Apache HTTPD)]

the same with the catalogs:

[root@cloudforms ~]# miqimport service_catalogs miq-RedHat-Satellite6/Catalogs/
rake aborted!
Errno::EISDIR: Is a directory @ io_fillbuf - fd:31 /root/miq-RedHat-Satellite6/Catalogs/v5.8
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_catalogs.rake:10:in `block in import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_catalogs.rake:8:in `foreach'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_catalogs.rake:8:in `import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_service_catalogs.rake:419:in `block (3 levels) in <top (required)>'
Tasks: TOP => rhconsulting:service_catalogs:import
(See full trace by running task with --trace)
[root@cloudforms ~]# miqimport service_catalogs miq-RedHat-Satellite6/Catalogs/v5.9
Service Catalog: [Hybrid Cloud VMs (My Company)]
Catalog Item: [Hybrid Cloud | RHEL (My Company)]
Catalog Item: [Hybrid Cloud | Apache HTTPD (My Company)]

Maybe the problem lies here?

**Comment by shs-mdro** [comment]
Sorry for spamming this thread but i have to ask this fundamental question.
Is your repo able to provision from a vmware template and register it to satellite6?
Because the description says something about PXE (Satellite 6 PXE & Kickstart based provisioning Service and VM state machines) and i'm questioning it right now, if I'm on the right track.

**Comment by A-Beck** [comment]
@shs-mdro Thanks for providing the RPM version. Yes, it looks like the appliances we are using are on the same version.

One of the reasons our dialogs look different is that I was taking my screenshots on a CFME 5.9 appliance. 

You are correct that you should go one level deeper to import dialogs - the following command is the one I ran to import the dialogs:
`miqimport service_dialogs miq-RedHat-Satellite6/Dialogs/v5.9/`

The instructions look out of date in this regard - I'll open an issue to fix the installation document.

Just to make sure we are working of the same dialogs, below is the one exported from my 5.10 appliance. You can import it via the UI by going to Automation -> Automate -> Customization -> import/export. Note that I had to add .txt to the file name to allow github to upload it.

[dialog_export_20190612_104320.yml.txt](https://github.com/RedHatOfficial/miq-RedHat-Satellite6/files/3280959/dialog_export_20190612_104320.yml.txt)

Unfortunately, you'll have to re-associate the catalog item with the dialog after importing, which can be done at Service -> Catalog -> Catalog Items -> Select RHEL catalog item -> Configuration Button -> Edit -> set dialog to 'Satellite Provisioning'. The below image has my catalog item configuration.

![image](https://user-images.githubusercontent.com/4661604/59346844-3a96c380-8ce1-11e9-9b1b-99152f89164b.png)

```
Is your repo able to provision from a vmware template and register it to satellite6?
```

Yes - you can see the basic outline of operations here ( which you seem to have already found ):
https://github.com/RedHatOfficial/miq-RedHat-Satellite6/blob/master/Automate/RedHatConsulting_Satellite6/Infrastructure/VM/Provisioning/StateMachines/VMProvision_VM.class/satellite.yaml#L25

The basic flow is:
+ Clones template to VM in your virtualization provider
+ Add Disk to VM
+ Register to Satellite
+ Power on VM and PXE boot
+ ( Optional ) Add more disks to VM

And here is the code that registers to satellite - note that the values in the host creation request sets build to true, which is where the Satellite build comes in.

https://github.com/RedHatOfficial/miq-RedHat-Satellite6/blob/master/Automate/RedHatConsulting_Satellite6/Integration/Satellite/Operations/Methods.class/__methods__/register_satellite.rb#L316


I am still confused as to why some values seem to be set, but others do not. From the logs you posted earlier:

```
----] I, [2019-06-07T09:28:53.745106 #6986:afa0244]  INFO -- : <AEMethod get_domains_by_location> Listing Current Object Attributes:
[----] I, [2019-06-07T09:28:53.747370 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_location_0_cloud_flavor: 
[----] I, [2019-06-07T09:28:53.748146 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_location_0_cloud_ssh_key: 
[----] I, [2019-06-07T09:28:53.748918 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_location_0_destination_network: 
[----] I, [2019-06-07T09:28:53.749674 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_location_0_domain_name: 
[----] I, [2019-06-07T09:28:53.750436 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_location_0_provisioning_network: 
[----] I, [2019-06-07T09:28:53.751216 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_location_1_cloud_flavor: 
[----] I, [2019-06-07T09:28:53.751976 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_location_1_cloud_ssh_key: 
[----] I, [2019-06-07T09:28:53.752742 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_location_1_destination_network: 
[----] I, [2019-06-07T09:28:53.753507 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_location_1_domain_name: 
[----] I, [2019-06-07T09:28:53.754277 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_location_1_provisioning_network: 
[----] I, [2019-06-07T09:28:53.755020 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_location_2_cloud_flavor: 
[----] I, [2019-06-07T09:28:53.755772 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_location_2_cloud_ssh_key: 
[----] I, [2019-06-07T09:28:53.756534 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_location_2_destination_network: 
[----] I, [2019-06-07T09:28:53.757271 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_location_2_domain_name: 
[----] I, [2019-06-07T09:28:53.757992 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_location_2_provisioning_network: 
[----] I, [2019-06-07T09:28:53.758725 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_location_tags: ["[]"]
[----] I, [2019-06-07T09:28:53.759432 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_number_of_vms: 1
[----] I, [2019-06-07T09:28:53.760150 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_option_0_number_of_sockets: 1
[----] I, [2019-06-07T09:28:53.760846 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_option_0_vm_memory: 2048
[----] I, [2019-06-07T09:28:53.761573 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_os_tag: os/rhel7
[----] I, [2019-06-07T09:28:53.762287 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_satellite_environment_id: !
[----] I, [2019-06-07T09:28:53.762982 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_satellite_hostgroup_id: 1
[----] I, [2019-06-07T09:28:53.763708 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_satellite_organization_id: 4
[----] I, [2019-06-07T09:28:53.764425 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_service_name: 
[----] I, [2019-06-07T09:28:53.765141 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_templates: INVALID SELECTION
    * Destination location(s) must be selected to determine valid destination providers.
[----] I, [2019-06-07T09:28:53.765831 #6986:afb07c0]  INFO -- : <AEMethod get_domains_by_location> 	dialog_vm_prefix: 
```

It looks like values are coming though for the satellite hostgroup and organization, but not the location, which is what is tripping us up.

When you get the time, I'd curious to see what the 'Basic' Tab looks like when you fill out your dialog. Below is what mine looks like when the template and domain dialog elements are able to be populated.

![image](https://user-images.githubusercontent.com/4661604/59347319-53ec3f80-8ce2-11e9-8049-4c9c72edc3db.png)

**Comment by shs-mdro** [comment]
the service dialog comes up like this:
![image](https://user-images.githubusercontent.com/51401910/59348665-fa9f0300-8d17-11e9-9d95-067c030bda2d.png)
and filled out, looks like that:
![image](https://user-images.githubusercontent.com/51401910/59348694-14404a80-8d18-11e9-9332-2ceb39df75f2.png)

**Comment by shs-mdro** [comment]
I've imported your service dialog and it fails with the same error message (Selected templates must be specified).

Attached the new log.
[automation.log](https://github.com/RedHatOfficial/miq-RedHat-Satellite6/files/3281132/automation.log)

Thanks for clarifying about the provisioning workflow.
I thought that it uses this rhel-template (which has already an installed os in it) as a basis for registering the host into satellite. This test satellite has no images/installation media/pxe-config, i don't know if thats associated with the problem or not. But for us it would be great to reuse the rhel-template, assign an ip (with a ddi provider like infoblox, but thats another story) and to register it to satellite.

**Comment by A-Beck** [comment]
@shs-mdro Looking at the latest logs you posted, it looks like the dialogs are now populating as expected, correct? It appears you were able to submit a provisioning request:

Location tags come through:
```
[----] I, [2019-06-12T13:48:08.837266 #6986:187a978]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> location_tags => ["location/bs"]
```

templates get set:
```
[----] I, [2019-06-12T13:48:08.932902 #6986:187a978]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> value => ---
- :provider: stevm004.testlab.local
  :name: rhel7_template
  :guid: 85cc3155-46f1-4084-ac6e-4af2fb80ea59
```

Then it hits the error when trying to provision, because the value is not passed through from the dialog:
```
[----] E, [2019-06-12T13:49:37.343274 #29876:a7c7c98] ERROR -- : Q-task_id([r1000000000030_service_template_provision_task_1000000000030]) <AEMethod create_provision_requests> Selected templates must be specified
```

( see dialog_templates=>nil )
```
[----] I, [2019-06-12T13:49:21.977555 #29876:f1ef64]  INFO -- : Q-task_id([r1000000000030_service_template_provision_task_1000000000030]) <AEMethod [/ManageIQ/Service/Provisioning/StateMachines/Methods/dialog_parser]> Starting 
[----] I, [2019-06-12T13:49:22.572462 #29876:ffb57c]  INFO -- : Q-task_id([r1000000000030_service_template_provision_task_1000000000030]) <AEMethod dialog_parser> dialog_options: {"dialog_service_name"=>"testvm02", "dialog_vm_prefix"=>"testvm02", "dialog_number_of_vms"=>1, "dialog_option_0_number_of_sockets"=>1, "dialog_option_0_vm_memory"=>2048, "dialog_os_tag"=>"os/rhel7", "dialog_satellite_organization_id"=>"4", "Array::dialog_location_tags"=>"location/bs", "dialog_satellite_environment_id"=>9, "dialog_satellite_hostgroup_id"=>1, "dialog_templates"=>nil, "dialog_location_0_domain_name"=>"testlab.local", "dialog_location_0_provisioning_network"=>nil, "dialog_location_0_destination_network"=>nil, "dialog_location_0_cloud_flavor"=>nil, "dialog_location_0_cloud_ssh_key"=>nil, "dialog_location_1_domain_name"=>nil, "dialog_location_1_provisioning_network"=>nil, "dialog_location_1_destination_network"=>nil, "dialog_location_1_cloud_flavor"=>nil, "dialog_location_1_cloud_ssh_key"=>nil, "dialog_location_2_domain_name"=>nil, "dialog_location_2_provisioning_network"=>nil, "dialog_location_2_destination_network"=>nil, "dialog_location_2_cloud_flavor"=>nil, "dialog_location_2_cloud_ssh_key"=>nil, "dialog_location_3_domain_name"=>nil, "dialog_location_3_provisioning_network"=>nil, "dialog_location_3_destination_network"=>nil, "dialog_location_3_cloud_flavor"=>nil, "dialog_location_3_cloud_ssh_key"=>nil, "dialog_disk_pre_kickstart_1_size"=>10, "dialog_disk_pre_kickstart_1_bootable"=>"t", "dialog_disk_post_kickstart_1_size"=>"", "dialog_disk_post_kickstart_2_size"=>"", "dialog_disk_post_kickstart_3_size"=>"", "request"=>"clone_to_service", :service_action=>"Provision",
```

I think you are hitting this bug, fixed in the latest CFME update:
- Bug:    https://bugzilla.redhat.com/show_bug.cgi?id=1710610
- Errata: https://access.redhat.com/errata/product/167/ver=/cf-me---4.7/x86_64/RHSA-2019:1429

Can you try upgrading to the latest 5.10.5 version of CloudForms, which was released earlier this week, and testing again?

If want to template that already has an OS installed in it, the basics that we have set up here should give you a start. You may want to run commands on the host with something like Ansible, etc to do your specific post-provisioning configuration work. This would require some custom modifications/additions to the VM provisioning state machine I pointed out earlier, though.

**Comment by shs-mdro** [comment]
it works!
latest cfme fixed the issue, thank you guys!

**Comment by itewk** [comment]
glad to here @shs-mdro. thanks for your participation in our little community.

**Comment by shs-mdro** [comment]
Hi Andrew

Do you have any issues concerning stuck deployment jobs?

From time to time (3 out of 10) my vm’s don’t get deployed and the counters run up to 100 till it times out.

Greetings

Michel Drozdz
Linux System Engineer
[cid:image001.png@01D56CAE.9742BBA0]

Sopra Steria
Aeschenplatz 13
4002 Basel – Switzerland
Phone: +41 58 201 04 81
michel.drozdz@soprasteria.com<http://@soprasteria.com> - www.soprasteria.ch<http://www.soprasteria.ch/>

Von: Andrew Becker <notifications@github.com>
Gesendet: Donnerstag, 13. Juni 2019 14:09
An: RedHatOfficial/miq-RedHat-Satellite6 <miq-RedHat-Satellite6@noreply.github.com>
Cc: DROZDZ Michel <michel.drozdz@soprasteria.com>; Mention <mention@noreply.github.com>
Betreff: Re: [RedHatOfficial/miq-RedHat-Satellite6] unable to set location_tag correctly / dialog_templates: INVALID SELECTION (#92)


@shs-mdro<https://github.com/shs-mdro> Looking at the latest logs you posted, it looks like the dialogs are now populating as expected, correct? It appears you were able to submit a provisioning request:

Location tags come through:

[----] I, [2019-06-12T13:48:08.837266 #6986:187a978]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> location_tags => ["location/bs"]

templates get set:

[----] I, [2019-06-12T13:48:08.932902 #6986:187a978]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> value => ---

- :provider: stevm004.testlab.local

  :name: rhel7_template

  :guid: 85cc3155-46f1-4084-ac6e-4af2fb80ea59

Then it hits the error when trying to provision, because the value is not passed through from the dialog:

[----] E, [2019-06-12T13:49:37.343274 #29876:a7c7c98] ERROR -- : Q-task_id([r1000000000030_service_template_provision_task_1000000000030]) <AEMethod create_provision_requests> Selected templates must be specified

( see dialog_templates=>nil )

[----] I, [2019-06-12T13:49:21.977555 #29876:f1ef64]  INFO -- : Q-task_id([r1000000000030_service_template_provision_task_1000000000030]) <AEMethod [/ManageIQ/Service/Provisioning/StateMachines/Methods/dialog_parser]> Starting

[----] I, [2019-06-12T13:49:22.572462 #29876:ffb57c]  INFO -- : Q-task_id([r1000000000030_service_template_provision_task_1000000000030]) <AEMethod dialog_parser> dialog_options: {"dialog_service_name"=>"testvm02", "dialog_vm_prefix"=>"testvm02", "dialog_number_of_vms"=>1, "dialog_option_0_number_of_sockets"=>1, "dialog_option_0_vm_memory"=>2048, "dialog_os_tag"=>"os/rhel7", "dialog_satellite_organization_id"=>"4", "Array::dialog_location_tags"=>"location/bs", "dialog_satellite_environment_id"=>9, "dialog_satellite_hostgroup_id"=>1, "dialog_templates"=>nil, "dialog_location_0_domain_name"=>"testlab.local", "dialog_location_0_provisioning_network"=>nil, "dialog_location_0_destination_network"=>nil, "dialog_location_0_cloud_flavor"=>nil, "dialog_location_0_cloud_ssh_key"=>nil, "dialog_location_1_domain_name"=>nil, "dialog_location_1_provisioning_network"=>nil, "dialog_location_1_destination_network"=>nil, "dialog_location_1_cloud_flavor"=>nil, "dialog_location_1_cloud_ssh_key"=>nil, "dialog_location_2_domain_name"=>nil, "dialog_location_2_provisioning_network"=>nil, "dialog_location_2_destination_network"=>nil, "dialog_location_2_cloud_flavor"=>nil, "dialog_location_2_cloud_ssh_key"=>nil, "dialog_location_3_domain_name"=>nil, "dialog_location_3_provisioning_network"=>nil, "dialog_location_3_destination_network"=>nil, "dialog_location_3_cloud_flavor"=>nil, "dialog_location_3_cloud_ssh_key"=>nil, "dialog_disk_pre_kickstart_1_size"=>10, "dialog_disk_pre_kickstart_1_bootable"=>"t", "dialog_disk_post_kickstart_1_size"=>"", "dialog_disk_post_kickstart_2_size"=>"", "dialog_disk_post_kickstart_3_size"=>"", "request"=>"clone_to_service", :service_action=>"Provision",

I think you are hitting this bug, fixed in the latest CFME update:

  *   Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1710610
  *   Errata: https://access.redhat.com/errata/product/167/ver=/cf-me---4.7/x86_64/RHSA-2019:1429

Can you try upgrading to the latest 5.10.5 version of CloudForms, which was released earlier this week, and testing again?

If want to template that already has an OS installed in it, the basics that we have set up here should give you a start. You may want to run commands on the host with something like Ansible, etc to do your specific post-provisioning configuration work. This would require some custom modifications/additions to the VM provisioning state machine I pointed out earlier, though.

**Comment by A-Beck** [comment]
@shs-mdro Feel free to open up another issue to get more in depth than my answer below.

I've only encountered 'stuck' deployment jobs when the satellite builds fails to complete. In satellite, the build will be marked as pending, then eventually expired.

I have not encountered the situation where the build successfully completed in satellite, but the provisioning request in CloudForms was stuck.

If you just need more time for the satellite builds to complete, you can override the state machine and increase the number of retires for the `CheckBuildCompleted` Step:
- https://github.com/RedHatOfficial/miq-RedHat-Satellite6/blob/master/Automate/RedHatConsulting_Satellite6/Infrastructure/VM/Provisioning/StateMachines/VMProvision_VM.class/satellite.yaml#L39

**Comment by shs-mdro** [comment]
Hi

It was something completely different:

They changed the certificate of the vcenter appliance and i readded the vcenter with the new cert and under a new name.
Everything works now as it should.

Thank you anyway!
