### ISSUE TITLE
NVALID SELECTION     * Destination location(s) must be selected to determine valid destination providers.

### ISSUE THREAD

**Issue by wkleinhenz** [RedHatOfficial/miq-RedHat-Satellite6#96]
Hi all,
Im attempting to implement the content in this repo. My current setup is:
Foreman 1.22.0
Vcenter 6.7u3
Manageiq ivanchuk-1-rc1.20190822144352_42f785c

i seem to be having an issue similar to #92, where i create and assign the tags but even when selecting the right location, os and environment the Providers and templates dont seem to populate with the error of NVALID SELECTION
    * Destination location(s) must be selected to determine valid destination providers.

ill attach the automate logs

any help is appreciated
 thanks

[automation (1).log](https://github.com/RedHatOfficial/miq-RedHat-Satellite6/files/3562984/automation.1.log)

**Comment by itewk** [comment]
@A-Beck @curt-matthews this something either of you can help out with?

**Comment by A-Beck** [comment]
@wkleinhenz Thanks for attaching the logs! Could you try to run through an order attempt with the debug flag set to `true` in this method, then upload logs again?

https://github.com/RedHatOfficial/miq-Utilities/blob/master/Automate/RedHatConsulting_Utilities/Service/Provisioning/DynamicDialogs.class/__methods__/get_templates_based_on_selected_os_and_location.rb#L8

**Comment by wkleinhenz** [comment]
Sure, I'll give it a shot after work, thanks for the help

**Comment by wkleinhenz** [comment]
Ok heres the new log file, i also took the liberty of also enabling debug on get_location.rb as it seems that the dialog location tags are being populated even though the tags seem to match the foreman side of things. Also a note the rhel7 template doesn't
[automation.log](https://github.com/RedHatOfficial/miq-RedHat-Satellite6/files/3572105/automation.log)
 actually exist and the tag inst used so those runs might not be of use.

**Comment by A-Beck** [comment]
Thanks for providing the log file, that is very helpful. Looking at that, it does indeed seem like location tags are not available to the method that is looking for providers:

```
----] I, [2019-09-03T19:34:51.250787 #2846:1057d57c]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> ===========================================
[----] I, [2019-09-03T19:34:51.251352 #2846:1057d57c]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> Listing Current Object Attributes:
[----] I, [2019-09-03T19:34:51.255496 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	dialog_disk_post_kickstart_1_size: 
[----] I, [2019-09-03T19:34:51.257174 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	dialog_disk_post_kickstart_2_size: 
[----] I, [2019-09-03T19:34:51.258616 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	dialog_disk_post_kickstart_3_size: 
[----] I, [2019-09-03T19:34:51.260241 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	dialog_disk_pre_kickstart_1_bootable: t
[----] I, [2019-09-03T19:34:51.261879 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	dialog_disk_pre_kickstart_1_size: 10
[----] I, [2019-09-03T19:34:51.263561 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	dialog_location_tags: []
[----] I, [2019-09-03T19:34:51.265206 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	dialog_number_of_vms: 1
[----] I, [2019-09-03T19:34:51.266899 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	dialog_option_0_number_of_sockets: 1
[----] I, [2019-09-03T19:34:51.269017 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	dialog_option_0_vm_memory: 2048
[----] I, [2019-09-03T19:34:51.270623 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	dialog_os_tag: os/rhel7
[----] I, [2019-09-03T19:34:51.272482 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	dialog_satellite_environment_id: 0
[----] I, [2019-09-03T19:34:51.274378 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	dialog_satellite_hostgroup_id: 1
[----] I, [2019-09-03T19:34:51.276279 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	dialog_satellite_organization_id: 3
[----] I, [2019-09-03T19:34:51.278351 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	dialog_service_name: 
[----] I, [2019-09-03T19:34:51.280259 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	dialog_templates: 
[----] I, [2019-09-03T19:34:51.282198 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	dialog_vm_prefix: 
[----] I, [2019-09-03T19:34:51.285357 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	miq_group: #<MiqAeMethodService::MiqAeServiceMiqGroup:0x000000001f57cb40>
[----] I, [2019-09-03T19:34:51.288163 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	miq_server: #<MiqAeMethodService::MiqAeServiceMiqServer:0x000000001f585448>
[----] I, [2019-09-03T19:34:51.290108 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	miq_server_id: 1
[----] I, [2019-09-03T19:34:51.291680 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	object_name: get_templates_based_on_selected_os_and_location
[----] I, [2019-09-03T19:34:51.294576 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	service_template: #<MiqAeMethodService::MiqAeServiceServiceTemplate:0x000000001f580ee8>
[----] I, [2019-09-03T19:34:51.296486 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	service_template_id: 2
[----] I, [2019-09-03T19:34:51.299346 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	tenant: #<MiqAeMethodService::MiqAeServiceTenant:0x000000001f57d018>
[----] I, [2019-09-03T19:34:51.302171 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	user: #<MiqAeMethodService::MiqAeServiceUser:0x000000001f57d518>
[----] I, [2019-09-03T19:34:51.304171 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	user_id: 1
[----] I, [2019-09-03T19:34:51.306154 #2846:10574a08]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> 	vmdb_object_type: service_template
[----] I, [2019-09-03T19:34:51.307825 #2846:1057d57c]  INFO -- : <AEMethod get_templates_based_on_selected_os_and_location> ===========================================
```
By any chance, is the location field outlined in red in the dialog? Attaching an image of the 1st tab of the dialog might be helpful.

I noticed a minor bug in the dropdown, fixed in this branch: https://github.com/RedHatOfficial/miq-RedHat-Satellite6/tree/fix-location-dialog-data-type

Can you give that branch a try, and see if you get any better results?

**Comment by wkleinhenz** [comment]
ok so i made the change in the branch, in addition to enabling debug mode in that method.
Below is a screenshot of the initial service order screen.


![image](https://user-images.githubusercontent.com/18507996/64302200-3a107080-cf50-11e9-8e4e-ddb683973d5a.png)

And it looks like that fixed that part of it works. However, I finish do the deployment as it seems like its asking for the following even when i select an option:
Number of Vms
CPUs
Memory
Org
Hostgroup

ill attach the automation log again just in case
[automation.log](https://github.com/RedHatOfficial/miq-RedHat-Satellite6/files/3576928/automation.log)

**Comment by A-Beck** [comment]
@wkleinhenz It looks like you are hitting this bug here:
+ https://bugzilla.redhat.com/show_bug.cgi?id=1740899

It looks like that bug will break any integer-values dialog elements, which number of VMs, CPUs, etc are.

It looks like that bug effects both Hammer and Ivanchuk.

Looking at the BZ, it looks like the fixes are merged in, so hopefully the next Ivanchuk RC will be fixed.
+ https://github.com/ManageIQ/manageiq-ui-classic/pull/6150
+ https://github.com/ManageIQ/manageiq-ui-service/pull/1585

I suppose we could change everything to strings, and do a bunch of casting, but that seems like a pretty ugly work-around for something that should be fixed soonish.

**Comment by wkleinhenz** [comment]
Ok cool, looks like everything related to this is fixed then, I'll keep an
eye out for the new miq version release.

Thanks for the help

**Comment by shs-mdro** [comment]
Hello everybody

Since I'm having the same issue: How do i update manage iq to include this fix?
Did anybody do these kind of (incremental) upgrades?

Greetings

Michel
